use core::marker::PhantomData;

use crate::{
    tls::msgs::RecordHeader,
    wire::{self, alert::Alert, ContentType, HandshakeHeader, HandshakeType, TryParse},
    Error,
};

pub(crate) enum Record<'a> {
    ChangeCipherSpec,
    Alert(Alert),
    Handshake(HandshakeHeader),
    ApplicationData(PhantomData<&'a ()>),
    Heartbeat,
}

impl Record<'_> {
    pub(crate) fn parse(hdr: RecordHeader, data: &[u8]) -> Result<Self, Error> {
        let record = match hdr.content_type {
            ContentType::Invalid => {
                // TODO(eric): is this the correct alert?
                return Err(wire::Error::illegal_parameter("invalid content type").into());
            }
            ContentType::ChangeCipherSpec => Self::ChangeCipherSpec,
            ContentType::Alert => Alert::try_parse_all(data).map(Self::Alert)?,
            ContentType::Handshake => HandshakeHeader::try_parse_all(data).map(Self::Handshake)?,
            ContentType::ApplicationData => Self::ApplicationData(PhantomData),
            ContentType::Heartbeat => Self::Heartbeat,
        };

        // RFC 8446: "legacy_record_version:  MUST be set to
        // 0x0303 for all records generated by a TLS 1.3
        // implementation other than an initial ClientHello
        // (i.e., one not generated after a HelloRetryRequest),
        // where it MAY also be 0x0301 for compatibility
        // purposes. This field is deprecated and MUST be ignored
        // for all purposes.  Previous versions of TLS would use
        // other values in this field under some circumstances."
        if hdr.legacy_record_version != wire::ProtocolVersion::Tls13
            && (hdr.legacy_record_version != wire::ProtocolVersion::Tls13
                || !record.is_client_hello())
        {
            // TODO(eric): Track whether or not this is the
            // initial ClientHello or not.
            return Err(wire::Error::protocol_version("invalid version").into());
        }
        Ok(record)
    }

    const fn is_client_hello(&self) -> bool {
        matches!(
            self,
            Record::Handshake(HandshakeHeader {
                msg_type: HandshakeType::ClientHello,
                ..
            })
        )
    }
}

// pub(crate) enum Handshake<'a> {
//     ClientHello(ClientHello<'a>),
//     ServerHello(ServerHello<'a>),
//     EndOfEarlyData,
//     EncryptedExtensions,
//     CertificateRequest,
//     Certificate,
//     CertificateVerify,
//     Finished,
//     NewSessionTicket,
//     KeyUpdate,
//     MessageHash,
// }

// impl<'a> Handshake<'a> {
//     pub(crate) fn parse(hdr: HandshakeHeader, data: &'a [u8]) -> Result<Self, Error> {
//         let hs = match hdr.msg_type {
//             HandshakeType::ClientHello => {
//                 ClientHello::try_parse_all(data).map(Self::ClientHello)?
//             }
//             HandshakeType::ServerHello => {
//                 ServerHello::try_parse_all(data).map(Self::ServerHello)?
//             }
//             HandshakeType::EndOfEarlyData => Self::EndOfEarlyData,
//             HandshakeType::EncryptedExtensions => Self::EncryptedExtensions,
//             HandshakeType::CertificateRequest => Self::CertificateRequest,
//             HandshakeType::Certificate => Self::Certificate,
//             HandshakeType::CertificateVerify => Self::CertificateVerify,
//             HandshakeType::Finished => Self::Finished,
//             HandshakeType::NewSessionTicket => Self::NewSessionTicket,
//             HandshakeType::KeyUpdate => Self::KeyUpdate,
//             HandshakeType::MessageHash => Self::MessageHash,
//         };
//         Ok(hs)
//     }
// }
